import { from } from "rxjs";

const targetSequence = `adjasdhsakdjsahdksahdaacdegfadnsakdjsakdhjasasdo
asdasjdhsadsaacdadasdasdasdasdasdanjakdashdkhaslkdhaskdhashdjashjcdlksahjdhaskljdhdsadsajdhsakdhjashdkashdlsajdd
adsaldkjsadkjlsahdjashjdklasjhdklashdklasdacdefggadjsakdhjsahdkjsaachdkjashldjhasjlkdhasldaaacdfegacacadasdasdasdascacadasdsdadasjhd
adascascacacadasdasdsadasacdefdasdsadsadasacadasdasdasacacacadasdsaacacacacacdasdasdjsakdksjfhldsjhflidshfldsfhisbhlfbslfblsjzfb;szfb
adnjkasdjlsahdljkashjkdhsakljdhkajsdhklasdhkjlacacacacacadhdkahdjlahdjlahlkdhaskjdhalksdhkalhdahacacacakchkashdlkahdkahjdkhakldhaslkhdac
acjkashkashljkdhaskjldhasldhsalkdhlkascacacsjhdalskdhkashdlkashdh`;
export const matchSequence = "acacac";
export const target$ = from(targetSequence);